version: 2
updates:
  # Enable version updates for pnpm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # This will also update the packageManager field and pnpm-lock.yaml
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Update package managers (including pnpm)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Monitor pnpm packages in subdirectories
  - package-ecosystem: "npm"
    directory: "/packages/angular"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "deps(angular)"
      prefix-development: "deps-dev(angular)"
    groups:
      angular-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "deps(react)"
      prefix-development: "deps-dev(react)"
    groups:
      react-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/vue"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "deps(vue)"
      prefix-development: "deps-dev(vue)"
    groups:
      vue-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/ssr"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "deps(ssr)"
      prefix-development: "deps-dev(ssr)"
    groups:
      ssr-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
