version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # This will also update the packageManager field
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Update package managers (including pnpm)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Explicitly monitor for pnpm updates in package.json packageManager field
  - package-ecosystem: "npm"
    directory: "/packages/angular"
    schedule:
      interval: "weekly"
    groups:
      angular-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "weekly"
    groups:
      react-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/vue"
    schedule:
      interval: "weekly"
    groups:
      vue-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/packages/ssr"
    schedule:
      interval: "weekly"
    groups:
      ssr-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
